runtime: nodejs14 # or another supported version

instance_class: F1

env_variables:
  ROUTER_STAT_URL: 'http://routerstat.appspot.com'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
