runtime: nodejs14 # or another supported version

instance_class: F4 # takes about 550MB of RAM to run (???)

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
