export const FETCH_USAGE_DATA_BEGIN = 'FETCH_USAGE_DATA_BEGIN';
export const FETCH_USAGE_DATA_SUCCESS = 'FETCH_USAGE_DATA_SUCCESS';
export const FETCH_USAGE_DATA_FAILURE = 'FETCH_USAGE_DATA_FAILURE';
